id: P006929
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS16803
  title: དབུ་མའི་གཞུང་དང་འགྲེལ་པ།
  author: ''
  volumes:
    c1387541f99a44f9bdacc437473afc1d:
      image_group_id: I8LS16809
      title: ''
      volume_number: 1
      total_pages: 58
      base_file: v001.txt
